### ISSUE TITLE
read_parquet does not retain `crs`

### ISSUE THREAD

**Issue by TomAugspurger** [geopandas/dask-geopandas#96] opened 2021-08-18 21:29 UTC
Currently, read_parquet loses the `crs` of the geometry column(s).

```python
In [1]: import geopandas, dask_geopandas

In [2]: df = geopandas.read_file(geopandas.datasets.get_path("naturalearth_lowres"))

In [3]: df.to_parquet("test.parquet")

In [4]: dask_geopandas.read_parquet("test.parquet").geometry.crs  # None
```

I'm looking into how best to handle this. I think all the information is there in the parquet file.

**Comment by jorisvandenbossche** [comment] 2021-08-19 06:23
Whoops, I would have thought that the `assert_geodataframe_equal` would have checked for the CRS, and that this was covred. But so it does do that, but the issue is that we are testing the computed result. And at that point, the resulting geopandas GeoDataFrame actually has the correct CRS .. (because at that points it gets it from the actual geometry array stored in the geometry column), but its the dask-geopandas GeoDataFrame that doesn't have the crs set (because here it's getting it from the `meta`, as you fixed in the PR). 

Thanks for the catch!

**Closed** 2021-08-20 10:40 UTC
